### ISSUE TITLE
Bug: invalid bomb count...

### ISSUE THREAD

**Issue by dkwolfe4** [mhuggins7278/games#5]
Nice minesweeper game... ran into one little issue with row 2 column 2 from upper left in this game, where the bomb count isn't accurate.  It should have been two and I clicked on the row 1 column 1 based on this square and got blown up..
![Screen Shot 2021-11-18 at 6 46 32 PM](https://user-images.githubusercontent.com/23007633/142556774-4aed614d-a7bf-4b43-a458-a9615604bd4c.png)
.

**Comment by mhuggins7278** [comment]
I was actually just looking at this. It should be fixed in this commit 595a1cfff75ae393f6b05ddbae3a3334bfbf902b . I was missing that first corner and the last corner in some cases.
